services:
  postgres:
    image: postgres:16
    container_name: mlvision_postgres
    restart: always
    environment:
      POSTGRES_DB: ml_vision
      POSTGRES_USER: mluser
      POSTGRES_PASSWORD: mlpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
